### ISSUE TITLE
Add an Interactions command

### ISSUE THREAD

**Issue by peterthehan** [cq-pandora/projects#1]
Allows users to see all the hero dialogues. Reference: https://johj.github.io/cqdb/interactions

Embed interface could show the dialogue text and you could generate an image that shows the involved heroes facing each other on top of a crop of the town background?

**Comment by truelecter** [comment]
Implemented in https://github.com/cq-pandora/projects/commit/3995f236c5d4553b4e2ea561949e8155aa67a604
