### ISSUE TITLE
[Feature Request] Localization support

### ISSUE THREAD

**Issue by peterthehan** [cq-pandora/projects#17]
As a user, I want to be able to pass a language argument to commands so that the information is localized.

Example:
`!hero lee` -> defaults to english
`!sb bihwa ko` -> outputs in korean
`!interactions shuwen ja` -> outputs in japanese

Reference for ISO-639-1 language codes:
https://cloud.google.com/translate/docs/languages

**Comment by truelecter** [comment]
Do you have any suggestions what to do when command has optional arguments?

**Comment by peterthehan** [comment]
If it were set to be the last argument for each command, I guess you could parse the argument list and see if it exists in a set of valid localization codes, otherwise, default to en.

```
function parseLocalizationCode(args) {
  lastArg = args[args.length - 1].toLowerCase()
  return isValidLocalizationCode(lastArg)
    ? lastArg
    : 'en'
}

function isValidLocalizationCode (code) {
  return code in LOCALIZATION_CODES
}
```

**Comment by peterthehan** [comment]
Also, I realized an alternative localization implementation could look like, `!hero 오시리스` (Osiris in korean)

**Comment by truelecter** [comment]
Yeah, thought that it may be hard for non-english users to type heroes name in english. Not sure how fuzzy search will work for other locales tho

**Comment by truelecter** [comment]
Not the fuzzy search itself, but how efficiently it will correct small mistakes as it does currently for english. Especially for locales that use non-letter characters

**Comment by truelecter** [comment]
Ok, so for the test I'll be using same translation language, as the language used in the query, but I'll need someone to test it for non-letter languages

**Comment by truelecter** [comment]
![image](https://user-images.githubusercontent.com/5520406/81774911-5c518980-94f4-11ea-8a20-e556472ba1cc.png)

So, this may be the problem. If the name of character is written in the same way on different languages...

May be adding something like emojis with flags so user can press them and embed will be edited to use different translation? And default language will be one used in query

**Comment by peterthehan** [comment]
That's another clever solution, though for other languages, finding info becomes a 2-step process (first invoke the command, then react with flag emoji)

**Comment by truelecter** [comment]
I meant that if you type 오시리스 (which I assume is Osiris, as you've said in previous comments), embed will be shown in korean, but flags will be still visible. 

And in case of conflicting names (let's assume that Sera is written Cera in french, german and italian languages) I'll be showing german translation (because de_de is the first in locales code if sorted alphabetically) by default and than user may use flag to translate it to french if they meant french translation. If one of the conflicting translations is english - I'll show it as default, despite it is going after de_de

**Comment by truelecter** [comment]
![image](https://user-images.githubusercontent.com/5520406/82128438-e7b46e80-97c3-11ea-9c96-f4cae472a02a.png)
![image](https://user-images.githubusercontent.com/5520406/82128452-01ee4c80-97c4-11ea-9275-eb1b9a07ccaa.png)

Here what I came up with for now. However, flag emoji are even for languages that do not have all the keys properly translated. I think I should remove some of them.

Another problem is that I do not have translations for command string that are written by myself (such as stat names, 'SBW Effect' and such). I'll try to find all available translations in game files, however others I'll be forced to translate via google translate

**Comment by peterthehan** [comment]
Yeah, one concern here is the number of emojis that flood the message, especially on mobile it might be a bit excessive.

**Comment by truelecter** [comment]
I've rolled out more-less stable version. You can now test it and suggest if there may be some better solution
