### ISSUE TITLE
Allow bot commands to work without the MANAGE_MESSAGES permission

### ISSUE THREAD

**Issue by peterthehan** [cq-pandora/projects#2]
The bot currently fails to send any meaningful message if it does not have the MANAGE_MESSAGES permission which is apparently required so that reacting with the trash can emoji deletes both the invoking command message and the bot's embed message.

It should handle this elegantly and instead just delete it's own embed and ignore the invoking command message if it does not have permission.

![image](https://user-images.githubusercontent.com/16639331/57589564-b0491d00-74f2-11e9-987e-dd64be247694.png)

**Comment by truelecter** [comment]
Not only it is required to delete initial message, but it is required to delete user reaction under bot's message: https://discordapp.com/developers/docs/resources/channel#delete-user-reaction

Anyways, now bot just do not delete user message and reaction if no MANAGE_MESSAGES permission available
